apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpa-scheduler
  namespace: todo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa-scheduler
  namespace: todo
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscaler
  verbs:
  - get
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-scheduler
  namespace: todo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpa-scheduler
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: hpa-scheduler
  namespace: todo
