apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: todo
  labels:
    app.kubernetes.io/name: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: todo
  labels:
    app.kubernetes.io/name: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: todo
  labels:
    app.kubernetes.io/name: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: ryojpn/todo-api
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: "500m"
              memory: "700Mi"
            requests:
              cpu: "300m"
              memory: "500Mi"
          env:
            - name: PORT
              value: "4000"
            - name: MONGODB_URL
              value: mongodb://mongo.todo.svc.cluster.local:27017
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: todosecret
                  key: MONGO_USERNAME
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: todosecret
                  key: MONGO_PASSWORD
            - name: MONGODB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: todosecret
                  key: MONGO_DBNAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: todosecret
                  key: JWT_SECRET
            - name: _DOMAIN
              valueFrom:
                secretKeyRef:
                  name: todosecret
                  key: DOMAIN
            - name: FRONTEND_URL
              value: https://$(_DOMAIN)
