apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ryojpn/todo-frontend
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "100m"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
