name: Build and Push to Docker Hub
on:
  push:
    branches:
    - main
env:
  REPOSITORY: todo
jobs:
  buildx:
    strategy:
      matrix:
        target:
        - frontend
        - api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build and push the Docker image
      run: |
        docker buildx build \
          --push \
          --platform=linux/amd64,linux/arm64 \
          -t ${{secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-${{ matrix.target }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-${{ matrix.target }}:${{ github.sha }} \
          ${{ matrix.target }}
