name: Build and Push to Docker Hub
on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  REPOSITORY: todo
jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        driver: docker-container

    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        context: backend/nodejs
        tags: |
          ${{secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-api
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-api:${{ github.sha }}
        cache-from: type=gha,scope=$GITHUB_REF_NAME-api
        cache-to: type=gha,scope=$GITHUB_REF_NAME-api,mode=max

  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        driver: docker-container

    - name: Build and push the base image without Buildx (faster)
      uses: docker/build-push-action@v4
      with:
        push: true
        context: frontend
        target: todo-frontend-builder
        tags: |
          ${{secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-frontend-builder
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-frontend-builder:${{ github.sha }}
        cache-from: type=gha,scope=$GITHUB_REF_NAME-frontend-builder
        cache-to: type=gha,scope=$GITHUB_REF_NAME-frontend-builder,mode=max

    - name: Build and push the production image with Buildx
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        context: frontend
        target: production
        tags: |
          ${{secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-frontend
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-frontend:${{ github.sha }}
