name: Build and Push to Docker Hub
on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  REPOSITORY: todo
jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build and push the Docker image
      run: |
        docker buildx build \
          --push \
          --platform=linux/amd64,linux/arm64 \
          -t ${{secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-api \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-api:${{ github.sha }} \
          api

  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the base image without Buildx (faster)
      run: |
        docker build \
          --push \
          --target todo-frontend-builder
          -t ${{secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-todo-frontend-builder \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-todo-frontend-builder:${{ github.sha }} \
          frontend

    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build and push the production image with Buildx
      run: |
        docker buildx build \
          --push \
          --target production \
          --platform=linux/amd64,linux/arm64 \
          -t ${{secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-frontend \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}-frontend:${{ github.sha }} \
          frontend
