name: Run Tests for Frontend and API
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  run_npm_test_for_frontend_and_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the most recent commit on this branch
        uses: actions/checkout@v3

      - name: Build and start the test env
        run: make test

      - name: Test frontend
        run: docker compose -f docker-compose-dev.yml exec -T frontend-test npm test -- --watchAll=false

      - name: Test api
        run: docker compose -f docker-compose-dev.yml exec -T api-test npm test -- --watchAll=false
